name: Release gem

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  push:
    if: github.repository == 'eval/uri-smtp'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      # Set up
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            fulcio.sigstore.dev:443
            github.com:443
            index.rubygems.org:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            rubygems.org:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@2e007403fc1ec238429ecaa57af6f22f019cc135 # v1.234.0
        with:
          bundler-cache: true
          ruby-version: ruby

      # Read version from version.rb
      - name: Get version
        id: version
        run: |
          version=$(ruby -r ./lib/uri/smtp/version -e 'puts URI::SMTP::VERSION')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      # Release
      - uses: rubygems/release-gem@1c162a739e8b4cb21a676e97b087e8268d8fc40b # v1.1.2

      # Job Summary
      - name: Summary
        run: |
          version="${{ steps.version.outputs.version }}"
          version_anchor="${version//./}"
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
          ## ✉️ URI::SMTP ${version}

          - **RubyGems**: https://rubygems.org/gems/uri-smtp/versions/${version}
          - **Changelog**: https://github.com/eval/uri-smtp/blob/main/CHANGELOG.md#${version_anchor}
          - **Attestation**: \`gem fetch uri-smtp -v ${version} && gh attestation verify uri-smtp-${version}.gem --owner eval\`
          EOF

      # GH Attestations
      - uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-path: pkg/*.gem

      # GH Release
      - name: Create GitHub release
        run: |
          version="${{ steps.version.outputs.version }}"
          dot_count=$(echo "$version" | tr -cd '.' | wc -c)

          read -r -d '' notes <<EOF || true
          ## ✉️ uri-smtp ${version}
          Address SMTP-servers as URI.

          **Rubygems**: https://rubygems.org/gems/uri-smtp/versions/${version}
          **Changelog**: https://github.com/eval/uri-smtp/blob/main/CHANGELOG.md#v${version//./}
          EOF

          if [[ "$dot_count" -gt 2 ]]; then
            gh release create "v$version" --verify-tag --prerelease --generate-notes
          else
            gh release create "v$version" --verify-tag --generate-notes --notes "$notes"
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
